name = "ImmuneReceptor"
uuid = "596bd1cf-497f-4349-8f50-b25beac56f74"
version = "0.1.0"
authors = ["KwatMDPhD"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Nucleus = "cd814215-3b54-4e50-ac5e-8a2c7852bc16"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25.122"
Graphs = "1.13.1"
MetaGraphsNext = "0.7.4"
ProgressMeter = "1.11.0"
Random = "1.11.0"
StatsBase = "0.34.6"
